### ISSUE TITLE
No such file or directory: '/tmp/Mesh_1.med'

### ISSUE THREAD

**Issue by coco20203030** [qingfengxia/quasi_static_metal_cutting#1]
after running  "metal_cut_ht_6.py"

Not enough input argument, Usage: `python - FenicsSolver case_input` 
  to run simulation
friction_heat_thickness, shear_heat_thickness 1.705e-05 0.000333689153025 7.94497983392e-05
calculated volume for shear, friction and chip: 4.24184574653e-11 1.13447157867e-11 3.968e-10
friction_mapping_gap_volume =  3.31423628095e-12
6.97245941981e-05 0.000796955758473
('check distannce must match, ', 0.00031, 0.000310013670298465)
============= analytical prediction =============
At the cutting position: Re = 33308.3520693, Pe = 21435.7523373
60.0626023645 33.3497005625
F_AB_1, F_secondary 349.497800361 434.521068273
heat generated from primary zone and secondary zone 1003.0016441 700.840432698
T_shear_interface =  283.685502679
T_friction_interface =  1333.78855691
runSalome running on adams-HP-ProBook-4530s
Searching for a free port for naming service: 2812 - OK
Searching Naming Service  + found in 0.1 seconds 
Searching /Registry in Naming Service  + found in 0.5 seconds 
Searching /Kernel/ModulCatalog in Naming Service  +th. 140069738157888 - Trace /home/A21173/smeca/yamm_build/V2019.0.3_pub_build/V2019_universal/modules/src/KERNEL/src/ModuleCatalog/SALOME_ModuleCatalog_Server.cxx [101] : Module Catalog Server: Naming Service was found
Warning: this type (Study,objref) already exists, it will be ignored.
Warning: this type (SALOME_MED/MEDCouplingFieldDoubleCorbaInterface,objref) already exists, it will be ignored.
 found in 0.5 seconds 
RunStudy
Searching /Study in Naming Service  + found in 0.5 seconds 
Searching /Containers/adams-HP-ProBook-4530s/FactoryServer in Naming Service  ++ found in 1.0 seconds 
Start SALOME, elapsed time :   2.7 seconds
First of all, os.chdir to the folder where salome_parameter.py is located
Traceback (most recent call last):
  File "/home/adams/PycharmProjects/quasi_static_metal_cutting/metal_cut_ht_6.py", line 200, in <module>
    generate_salome_mesh('salome_mesh_metal_cut.py')
  File "/home/adams/PycharmProjects/quasi_static_metal_cutting/utility.py", line 35, in generate_salome_mesh
    check_mtime(smesh_file)
  File "/home/adams/PycharmProjects/quasi_static_metal_cutting/utility.py", line 84, in check_mtime
    modified_time = os.path.getmtime(filename)
  File "/home/adams/PycharmProjects/quasi_static_metal_cutting/venv/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] No such file or directory: '/tmp/Mesh_1.med'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by qingfengxia** [comment]
I think python2 is not supported. It takes a bit time to understand how to run this code, as it is not a proper open source project but code.


Qingfeng Xia
Senior Research Software Engineer, Culham Centre of Fusion Energy, UKAEA

https://github.com/qingfengxia
https://www.researchgate.net/profile/Qingfeng_Xia
personal website: https://www.iesensor.com

________________________________

**Comment by coco20203030** [comment]
hello
what should I use python3 doesn't work with fenics 2017.2 ?
in readme file.. I found python2 or python3

thank you

**Comment by qingfengxia** [comment]
do try higher version of fenics and py3, there may be only tiny incompatible, you can fix it,  Fenics is a good research tool worth of your learning time

________________________________
